#!/bin/bash
echo Starting virtual environment...
source .env/bin/activate
source /opt/intel/oneapi/compiler/latest/env/vars.sh
source /opt/intel/oneapi/mkl/latest/env/vars.sh
python -c "import sys;print('Global\tPython: \t%s\nCurrent\tPython: \t%s\nIn Virtual Environment:\t%s'%(sys.base_prefix, sys.prefix,sys.prefix != sys.base_prefix))"
bash
